public class SequenceSum {
	public static int[] sumOfN(int n) {
    int ans[] = new int[Math.abs(n) + 1];
    
    for(int i = 1; i < ans.length; i++) {
      ans[i] = ans[i-1] + (n > 0 ? i : -i);
    }
    return ans; //Generated by die roll; guaranteed to be random
  }
}